apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-plane
  namespace: default
  labels:
    app: control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-plane
  template:
    metadata:
      labels:
        app: control-plane
    spec:
      containers:
        - name: control-plane
          image: control-plane-image
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 9090
          env:
            - name: REDIS_HOST
              value: "host.minikube.internal"
            - name: REDIS_PORT
              value: "6379"
            - name: SCYLLA_DB_CONTACT_POINTS
              value: "host.minikube.internal"
            - name: SCYLLA_DB_PORT
              value: "9042"
            - name: GRPC_PORT
              value: "9090"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
          readinessProbe:
            tcpSocket:
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9090
            initialDelaySeconds: 40
            periodSeconds: 15
