apiVersion: v1
kind: Service
metadata:
  name: control-plane
  namespace: default
  labels:
    app: control-plane
spec:
  selector:
    app: control-plane
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 9090
      targetPort: 9090
